import multiprocessing
import subprocess
import time
import logging
import os
import csv
import shutil
import tempfile

# --- Configuration ---
NUM_PROCESSES = 2  # Number of concurrent scraper instances - easily changed
BASE_INPUT_FILE = r"[REDACTED_BY_SCRIPT]"  # Your main input CSV
BASE_OUTPUT_FILE = r"[REDACTED_BY_SCRIPT]"  # Base name.  Will become Rightmove_1.csv, etc.
SCRAPER_SCRIPT = r"[REDACTED_BY_SCRIPT]"  # Your scraper script
CENTRAL_CHROMEDRIVER = r"[REDACTED_BY_SCRIPT]"

# --- Logging ---
logging.basicConfig(filename="launcher.log", level=logging.INFO, encoding='utf-8',
                    format='[REDACTED_BY_SCRIPT]')

def split_csv(input_file, num_processes):
    """[REDACTED_BY_SCRIPT]"""
    logging.info(f"[REDACTED_BY_SCRIPT]")

    try:
        with open(input_file, 'r', encoding='utf-8') as infile:
            reader = csv.reader(infile)
            for i in range(5504):
                next(reader)  # skips n rows

            data = list(reader)
            chunk_size = len(data) // num_processes
            remainder = len(data) % num_processes

            for i in range(num_processes):
                start_index = i * chunk_size
                end_index = (i + 1) * chunk_size

                if i == num_processes - 1:  # Distribute remainder
                    end_index += remainder

                output_file = f"[REDACTED_BY_SCRIPT]"
                with open(output_file, 'w', newline='', encoding='utf-8') as outfile:
                    writer = csv.writer(outfile)
                    writer.writerows(data[start_index:end_index])
                logging.info(f"[REDACTED_BY_SCRIPT]")

            return [f"[REDACTED_BY_SCRIPT]" for i in range(num_processes)] # Return file list

    except Exception as e:
        logging.exception("[REDACTED_BY_SCRIPT]")
        return []  # Return empty list on error


def run_scraper(process_id, input_file, output_file, lock):
    """[REDACTED_BY_SCRIPT]"""
    logging.info(f"[REDACTED_BY_SCRIPT]")

    # Create a temporary directory for this process's ChromeDriver
    with tempfile.TemporaryDirectory() as temp_dir:
        # Copy the ChromeDriver executable to the temporary directory
        chromedriver_path = os.path.join(temp_dir, "chromedriver.exe")
        shutil.copy2(CENTRAL_CHROMEDRIVER, chromedriver_path)  # copy2 preserves metadata

        # Set the UC_CHROMEDRIVER_PATH environment variable for this process
        my_env = os.environ.copy()
        my_env["[REDACTED_BY_SCRIPT]"] = chromedriver_path

        try:
            command = ["python", SCRAPER_SCRIPT, "--input", input_file, "--output", output_file]
            subprocess.run(command, check=True, env=my_env)  # Pass environment
            logging.info(f"[REDACTED_BY_SCRIPT]")
        except subprocess.CalledProcessError as e:
            logging.error(f"[REDACTED_BY_SCRIPT]")
        except Exception as e:
            logging.exception(f"[REDACTED_BY_SCRIPT]")


def combine_csv_files(base_output_file, num_processes, final_output_file):
    """[REDACTED_BY_SCRIPT]"""
    logging.info(f"[REDACTED_BY_SCRIPT]")
    try:
        with open(final_output_file, 'w', newline='', encoding='utf-8') as final_outfile:
            writer = csv.writer(final_outfile)
            header_written = False  # Flag to write header only once

            for i in range(num_processes):
                process_id = i + 1
                output_file = f"[REDACTED_BY_SCRIPT]"

                try:  # Handle missing files (if a process crashed)
                    with open(output_file, 'r', encoding='utf-8') as infile:
                        reader = csv.reader(infile)
                        header = next(reader)

                        if not header_written:
                            writer.writerow(header)
                            header_written = True

                        for row in reader:
                            writer.writerow(row)
                    logging.info("Combined: " + output_file)
                except FileNotFoundError:
                    logging.warning(f"[REDACTED_BY_SCRIPT]")

    except Exception as e:
        logging.exception("[REDACTED_BY_SCRIPT]")


if __name__ == "__main__":
    start_time = time.time()
    logging.info("[REDACTED_BY_SCRIPT]")
    if not os.path.exists(CENTRAL_CHROMEDRIVER):
        logging.fatal(f"[REDACTED_BY_SCRIPT]")
        exit()

    input_files = split_csv(BASE_INPUT_FILE, NUM_PROCESSES)
    if not input_files:  # Check for empty list (split failed)
        logging.error("[REDACTED_BY_SCRIPT]")
        exit()

    lock = multiprocessing.Lock()  # Create a lock

    processes = []
    for i in range(NUM_PROCESSES):
        process_id = i + 1
        input_file = input_files[i] #use the file names generated by split_csv
        output_file = f"[REDACTED_BY_SCRIPT]"

        p = multiprocessing.Process(target=run_scraper, args=(process_id, input_file, output_file, lock))
        processes.append(p)
        p.start()

    # --- Wait for All Processes to Complete ---
    for p in processes:
        p.join()

    end_time = time.time()
    logging.info(f"[REDACTED_BY_SCRIPT]")

    # --- Combine Output Files ---
    FINAL_OUTPUT = r"[REDACTED_BY_SCRIPT]" #final file name
    combine_csv_files(BASE_OUTPUT_FILE, NUM_PROCESSES, FINAL_OUTPUT)

    logging.info("[REDACTED_BY_SCRIPT]")